recsys/recsys/user/models.py
# -*- coding: utf-8 -*-

"""
recsys.user.models
~~~~~~~~~~~~~~~~~~

User models.

:copyright: (c) 2020 by TzeSing.
:license: Apache2, see LICENSE for more details.
"""

from flask_login import UserMixin
from recsys.database import (
    Column,
    Model,
    SurrogatePK,
    db,
)
from sqlalchemy.dialects.mysql import DOUBLE


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = "users"
    username = Column(db.String(80), unique=True, nullable=False)

    def __init__(self, username, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return "<User({!r})>".format(self.username)


class Movies(SurrogatePK, Model):
    """Movies table"""

    __tablename__ = "movies"
    movie_name = Column(db.String(254))

    def __init__(self, movie_name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, movie_name=movie_name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return "<Movies({!r})>".format(self.movie_name)


class Ratings(SurrogatePK, Model):
    """Ratings table"""

    __tablename__ = "ratings"
    uid = Column(db.Integer, nullable=False)
    mid = Column(db.Integer, nullable=False)
    score = Column(DOUBLE, nullable=False)

    def __repr__(self):
        """Represent instance as a unique string."""
        return "<Ratings({},{},{})>".format(self.uid, self.mid, self.score)

recsys/recsys/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField(
        "Username", validators=[DataRequired(), Length(min=3, max=25)]
    )

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered, please login")
            return False
        return True

recsys/recsys/__init__.py
"""
recsys.__init__
~~~~~~~~~~~~~~~~~

Main application package.

:copyright: (c) 2020 by TzeSing.
:license: Apache2, see LICENSE for more details.
"""

recsys/recsys/app.py
# -*- coding: utf-8 -*-

"""
recsys.app
~~~~~~~~~~~~~~~~~~~

The app module, containing the app factory function.

:copyright: (c) 2020 by TzeSing.
:license: Apache2, see LICENSE for more details.
"""

import logging
import sys

from flask import Flask, render_template
from flask_wtf.csrf import generate_csrf
from recsys import commands, public, user
from recsys.extensions import (
    cache,
    csrf_protect,
    db,
    debug_toolbar,
    flask_static_digest,
    login_manager,
    migrate,
)


def create_app(config_object="recsys.settings"):
    """Create application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :Args
        config_object: The configuration object to use.
    """
    app = Flask(__name__.split(".")[0])
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    register_shellcontext(app)
    register_commands(app)
    configure_logger(app)

    @app.after_request
    def after_request(response):
        # 调用函数生成 csrf_token
        csrf_token = generate_csrf()
        # 通过 cookie 将值传给前端
        response.set_cookie("csrf_token", csrf_token)
        return response
    return app


def register_extensions(app):
    """Register Flask extensions."""
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    flask_static_digest.init_app(app)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""

    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, "code", 500)
        return render_template(f"{error_code}.html"), error_code

    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""

    def shell_context():
        """Shell context objects."""
        return {"db": db, "User": user.models.User,
                "Movies": user.models.Movies, "Ratings": user.models.Ratings}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.test)
    app.cli.add_command(commands.lint)


def configure_logger(app):
    """Configure loggers."""
    handler = logging.StreamHandler(sys.stdout)
    if not app.logger.handlers:
        app.logger.addHandler(handler)

recsys/recsys/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

recsys/recsys/user/views.py
# -*- coding: utf-8 -*-

"""
recsys.user.views
~~~~~~~~~~~~~~~~~

User views.

:copyright: (c) 2020 by TzeSing.
:license: Apache2, see LICENSE for more details.
"""

from flask import Blueprint, render_template, jsonify, request
from flask_login import login_required
from recsys.extensions import db

blueprint = Blueprint("user", __name__, url_prefix="/users",
                      static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")


@blueprint.route('/rate_history/', methods=['POST'])
def rate_history():
    """用户的评分记录"""
    params = request.get_json()
    username = params['username']

    sql = 'SELECT id FROM users WHERE username="{}"'.format(username)
    uid = db.session.execute(sql).fetchone()[0]
    sql = 'SELECT mid, score FROM ratings where uid={}'.format(str(uid))
    mid_score_pairs = db.session.execute(sql).fetchall()
    # unzip
    movies = []
    scores = []
    for pair in mid_score_pairs:
        mid, score = pair
        sql = 'SELECT movie_name FROM movies WHERE id={}'.format(mid)
        try:
            movie = db.session.execute(sql).fetchone()[0]
            movies.append(movie)
            scores.append(score)
        except:
            pass
    return jsonify({'movies': movies, 'scores': scores})

recsys/recsys/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>请先登录. 点击跳转<a href="{{ url_for('public.home')}}">登录</a>页面或者去<a href="{{ url_for('public.register') }}">注册</a>新账号.
        </p>
    </div>
</div>
{% endblock %}

recsys/recsys/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© 2020. TzeSing</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:jjzzxx000@outlook.com">Contact</a></li>
    </ul>
  </small>
</footer>

recsys/recsys/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{ static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %}
        RecSys
      {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}"/>
    <meta name="author" content="TzeSing" />
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />
    <link rel="stylesheet" type="text/css" href="{{ static_url_for('static', filename='build/style.css') }}">
    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %}
    {% with form=form %}
      {% include "nav.html" %}
    {% endwith %}

    <header>{% block header %}  {% endblock %}</header>

    <main role="main" id="main-role">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
          <div class="col-md-12">
            <!-- 轮流打出消息 -->
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert"
                >&times;</a
              >
              {{ message }}
            </div>
            <!-- end .alert -->
            {% endfor %}
          </div>
          <!-- end col-md -->
        </div>
        <!-- end row -->
        {% endif %}
      {% endwith %}

      {% block content %}

      {% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

recsys/recsys/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     RecSys
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" id="username" href="{{ url_for('user.members') }}" data-value="{{ current_user.username }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="username", class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}"><button type="button" class="btn btn-light">Register</button></a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>

recsys/recsys/templates/users/members.html
{% extends "layout.html" %}

{% block content %}
{% block header %}
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
{% endblock %}
<div class="jumbotron" id="login-welcome">
  <div class="container">
    <h1 class="display-3" style="color: #ffffff;">Welcome '{{ current_user.username }}'</h1>
    <p style="color: #ffffff;">This is the members-only page.</p>
  </div>
</div>
<div class="container">
  <span>评分历史:</span>
  <ul class="list-group">
<!--    {% for movie in popular5_movies %}-->
<!--    <li class="list-group-item">-->
<!--      <a href="/movie_info/{{ movie[0] }}">-->
<!--        <strong>{{ movie[1] }}</strong>-->
<!--      </a>-->
<!--      <span class="badge">评分人数：{{ movie[2] }}</span>-->
<!--    </li>-->
<!--    {% endfor %}-->
  </ul>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function () {
    var username = $("#username").attr("data-value");
    var csrftoken = "{{ csrf_token() }}"
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      }
    })
    $.ajax({
        type: "POST",
        url: "/users/rate_history/",
        dataType: "json",
        contentType: 'application/json; charset=UTF-8',
        data: JSON.stringify({
          username: username
        }),
        success(data) {
          for (var i = 0; i < data.movies.length; i++) {
            $('<li class="list-group-item"><strong>' + data.movies[i] + '<span class="badge">评分:' + data.scores[i] + '.0</span></strong></li>').appendTo('.list-group');
          }
        }
      })
  })
</script>
{% endblock %}

recsys/recsys/templates/users/movie_info.html
{% extends "layout.html" %}

{% block content %}
{% block header %}
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<style>
  .fixed-top {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1030;
  }
  .navbar-expand-lg .navbar-collapse {
    display: -ms-flexbox !important;
    display: flex !important;
    -ms-flex-preferred-size: auto;
    flex-basis: auto;
  }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    font-size: 1.5rem;
    line-height: 1.5;
    font-weight: 400;
    background-color: #fff;
    color: #212529;
    text-align: left;
  }
  .jumbotron {
    padding: 12rem 1rem;
    margin-bottom: 0;
    background-color: #e9ecef;
    border-radius: 0.3rem;
  }
  .divider-1 span {
    display: inline-block;
    width: 200px;
    height: 1px;
    background: #ddd;
  }
</style>
{% endblock %}
<div class="jumbotron" id="login-welcome" style="margin-top: -20px;" data-value="{{ csrf_token() }}">
  <div class="container">
    <h1 class="display-3" id="movie_name" data-value="{{ mid }}" style="color: #ffffff;">{{ movie_name }}</h1>
    <p style="color: #ffffff;">需要登录后才能评分.(已经登录请忽略)</p>
  </div>
</div>

<div class="value-props" style="padding: 20px 0; background: #f8f8f8;">
  <div class="container" style="padding: 5rem 0 5rem;">
    <div class="row">
      <div class="col-md-2">
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <br>
        <span class="badge">{{ score_dict[5.0] }} 人评价</span>
      </div>
      <div class="col-md-2">
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <br>
        <span class="badge">{{ score_dict[4.0] }} 人评价</span>
      </div>
      <div class="col-md-2">
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <br>
        <span class="badge">{{ score_dict[3.0] }} 人评价</span>
      </div>
      <div class="col-md-2">
        <i class="fa fa-star" aria-hidden="true"></i>
        <i class="fa fa-star" aria-hidden="true"></i>
        <br>
        <span class="badge">{{ score_dict[2.0] }} 人评价</span>
      </div>
      <div class="col-md-2">
        <i class="fa fa-star" aria-hidden="true"></i>
        <br>
        <span class="badge">{{ score_dict[1.0] }} 人评价</span>
      </div>
    </div>
  </div>
</div>

<div class="section-container" style="padding: 20px 0;">
  <div class="container" style="padding: 0rem 0 3rem; min-height: 30rem; position: relative;">
    <div style="display: flex; align-items: center; justify-content: center;">
      <h2 style="font-weight: 300;">点击下面按钮进行评分</h2>
    </div>
    <div class="divider-1 wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp; margin-bottom: 20px; display: flex; align-items: center; justify-content: center;"><span></span></div>
    <div class="badges-line" style="display: flex; align-items: center; justify-content: center;">
      <div class="btn-group btn-group-lg" role="group" aria-label="..." style="">
        <button type="button" class="btn btn-default" value="1">1</button>
        <button type="button" class="btn btn-default" value="2">2</button>
        <button type="button" class="btn btn-default" value="3">3</button>
        <button type="button" class="btn btn-default" value="4">4</button>
        <button type="button" class="btn btn-default" value="5">5</button>
      </div>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 20px;">
  <ul class="list-group" id="recommend">

  </ul>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function () {
    $('.btn').click(function (event) {
      var username = $("#username").attr("data-value");
      var mid = $("#movie_name").attr("data-value");
      var score = $(this).attr("value");
      var csrftoken = "{{ csrf_token() }}"
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken)
              }
          }
      })
      $.ajax({
        type: "POST",
        url: "/rate_movie/",
        dataType: "json",
        contentType: 'application/json; charset=UTF-8',
        data: JSON.stringify({
          username: username,
          mid: mid,
          score: score
        }),
        success(data) {
          alert("评分成功");
          alert("稍等5秒会产生准实时推荐")
          // 推荐
          $.ajax({
            type: "POST",
            url: "/get_realtime_rec/",
            dataType: "json",
            contentType: 'application/json; charset=UTF-8',
            data: JSON.stringify({
              username: username,
              mid: mid,
            }),
            success(data) {
              $('.value-props').hide()
              $('.section-container').hide()
              for (var i = 0; i < data.movie_name_recs.length; i++) {
                $('#recommend').append('<li class="list-group-item"><a href="#"><strong>' + data.movie_name_recs[i] + '</strong></a></li>')
              }
            }
          })
        }
      })
    });
  })
</script>
{% endblock %}

recsys/recsys/templates/users/movie_rec.html
{% extends "layout.html" %}

{% block content %}
<div class="jumbotron" id="login-welcome" style="margin-top: -30px;">
  <div class="container">
    <h1 class="display-3" style="color: #ffffff;">你可能感兴趣的电影</h1>
    <p style="color: #ffffff;">This is the members-only page.</p>
  </div>
</div>
<div class="container">
  <ul class="list-group">
    {% for pair in pairs %}
    <li class="list-group-item">
      <a href="/movie_info/{{ pair[1] }}">
        <strong>{{ pair[0] }}</strong>
      </a>
      <span class="badge"></span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

recsys/recsys/templates/users/popular.html
{% extends "layout.html" %}

{% block content %}
<div class="jumbotron" id="login-welcome" style="margin-top: -30px;">
  <div class="container">
    <h1 class="display-3" style="color: #ffffff;">Popular page</h1>
    <p style="color: #ffffff;">This is the members-only page.</p>
  </div>
</div>
<div class="container">
  <ul class="list-group">
    {% for movie in popular5_movies %}
    <li class="list-group-item">
      <a href="/movie_info/{{ movie[0] }}">
        <strong>{{ movie[1] }}</strong>
      </a>
      <span class="badge">评分人数：{{ movie[2] }}</span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

recsys/recsys/templates/users/real_time.html
{% extends "layout.html" %}

{% block content %}
{% block header %}
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<style>
  .navbar {
    position: fixed;
  }
  .fixed-top {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1030;
  }
  .navbar-expand-lg .navbar-collapse {
    display: -ms-flexbox !important;
    display: flex !important;
    -ms-flex-preferred-size: auto;
    flex-basis: auto;
  }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    font-size: 1.5rem;
    line-height: 1.5;
    font-weight: 400;
    background-color: #fff;
    color: #212529;
    text-align: left;
  }
  .jumbotron {
    padding: 12rem 1rem;
    margin-bottom: 0;
    background-color: #e9ecef;
    border-radius: 0.3rem;
  }
  .divider-1 span {
    display: inline-block;
    width: 200px;
    height: 1px;
    background: #ddd;
  }
</style>
{% endblock %}
<div class="jumbotron" id="login-welcome" style="margin-top: -30px;">
  <div class="container">
    <h1 class="display-3" style="color: #ffffff;">实时推荐</h1>
    <p style="color: #ffffff;">This is the members-only page.</p>
  </div>
</div>
<div class="search" style="margin-top: 50px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <input type="text" class="form-control" id="search" placeholder="搜索电影">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div><!-- /input-group -->
      </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function () {
    var csrftoken = "{{ csrf_token() }}"
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      }
    })
    $(".btn").click(function (event) {
      var movie_name = $("#search").val();
      $.ajax({
        type: "POST",
        url: "/search/",
        dataType: "json",
        contentType: 'application/json; charset=UTF-8',
        data: JSON.stringify({
          movie_name: movie_name
        }),
        success(data) {
          console.log(data.mid);
          window.location.href = '/movie_info/' + data.mid;
        }
      })
    })
  })
</script>
{% endblock %}